version: "2"
services:
        nodeserver:
                build:
                        context: ./app
                ports:
                        - "5000:5000"
        nginix:
                restart: always
                build:
                        context: ./nginx
                ports:
                        - "80:80"
                        - "443:443"
                volumes:
                        - ./nginx/nginx.conf:/etc/nginx/nginx.conf
                        - ./nginx/error.log:/etc/nginx/error_log.log
                        - /etc/letsencrypt/:/etc/letsencrypt/