version: "2"
services:
        nodeserver:
                build:
                        context: ./app
                ports:
                        - "5000:5000"
                image: techino/nodeapp
        nginix:
                restart: always
                build:
                        context: ./nginx
                ports:
                        - "80:80"
                        - "443:443"
                image: techino/nginxapp